Metadata(name='MOTSChallenge_val', thing_classes=['None', 'Car', 'Pedestrian'])
Loading sequence 0002
Loading sequence 0005
Loading sequence 0009
Loading sequence 0011
0002
0005
0009
0011
Loaded 2862 images!
../mask_rcnn_R_50_FPN_3x_MOTS/output/model_final.pth
Loading sequence 0002
Loading sequence 0005
Loading sequence 0009
Loading sequence 0011
0002
0005
0009
0011
Loaded 2862 images!
[5m[31mWARNING[0m [32m[03/26 12:44:17 d2.evaluation.coco_evaluation]: [0mjson_file was not found in MetaDataCatalog for 'MOTSChallenge_val'. Trying to convert it to COCO format ...
[5m[31mWARNING[0m [32m[03/26 12:44:17 d2.data.datasets.coco]: [0mUsing previously cached COCO format annotations at '../mask_rcnn_R_50_FPN_3x_MOTS/output/MOTSChallenge_val_coco_format.json'. You need to clear the cache file if your dataset has been modified.
